### PR TITLE
Release Bump 3.2.1

### PR DESCRIPTION
**Pull request by raghavaggarwal2308**
#### Summary
- https://github.com/mattermost/mattermost-plugin-azure-devops/pull/160
- https://github.com/mattermost/mattermost-plugin-azure-devops/pull/156
- https://github.com/mattermost/mattermost-plugin-azure-devops/pull/162

### CODE REVIEW

**Review by mickmister — APPROVED** [review]

**Comment by AayushChaudhary0001** [comment]
@raghavaggarwal2308 While testing this PR, it was found that the PR for adding whitespacing for the toggle button was not working, please check it once. After that we can proceed with further testing.

**Comment by raghavaggarwal2308** [comment]
> @raghavaggarwal2308 While testing this PR, it was found that the PR for adding whitespacing for the toggle button was not working, please check it once. After that we can proceed with further testing.

@AayushChaudhary0001  Fixed here: https://github.com/mattermost/mattermost-plugin-azure-devops/pull/162

**Review by AayushChaudhary0001 — APPROVED** [review]
This PR has been tested for the following scenarios:-

- Fixed the spacing between the toggle button and label.
- Fixed the allowance of 0 from middle to end.
- Basic slash commands and features.

The PR was found working fine for the above scenarios, LGTM. Approved.

**Pull request merged**
